config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions, only: [:new, :create, :index] do
    resources :answers, only: [:new, :create] do
      resources :corrects, only: [:new, :create]
    end
  end
  post 'corrects/moderate'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :corrects, dependent: :destroy
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/correct.rb
class Correct < ApplicationRecord
  belongs_to :answer
  validates :body, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  has_many :answers, dependent: :destroy
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.author = current_user.name
    @answer.save
    redirect_to questions_url
  end

  private

  def answer_params
    params.require(:answer).permit(:question, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/corrects_controller.rb
class CorrectsController < ApplicationController
  def new
    @correct = Correct.new
  end

  def create
    @answer = Answer.find(params[:answer_id])
    @correct = @answer.corrects.new(correct_params)
    @correct.author = current_user.name
    @correct.save
    redirect_to questions_url
  end

  def moderate
    @correct = Correct.find(params[:id])
    @correct.update_attributes(:moderate => true)
    redirect_to questions_url
  end

  private

  def correct_params
    params.require(:correct).permit(:answer, :body, :moderate)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  def index
    @questions = Question.order('created_at DESC')

    respond_to do |format|
      format.html
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.valid? and user_signed_in?
        @question.user_id = current_user.id
        @question.author = current_user.name
        @question.save
        format.html { redirect_to questions_url }
      else
        format.html { render action: 'new' }
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<%= form_for :answer, url: {action: "create"} do |f| %>
    <% if @answer && @answer.errors.any? %>
      <p>
        <ul>
          <% @answer.errors.full_messages.each do |msg|%>
            <li><%= msg %> </li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>
<% end %>

app/views/corrects/new.html.erb
<%= form_for :correct, url: {action: "create"} do |f| %>
    <% if @correct && @correct.errors.any? %>
      <p>
        <ul>
          <% @correct.errors.full_messages.each do |msg|%>
            <li><%= msg %> </li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Support</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <%= link_to('Create question', new_question_path, method: :get) %>
<% else %>
  <%= link_to('Login', new_user_session_path)  %> |
  <%= link_to('Sign Up', new_user_registration_path)  %>
<% end %>

<h1> Question </h1>
<% @questions.each do |question| %>
  <p>
    <strong>Question by:</strong>
    <%= question.author %>
  </p>

  <p>
    <%= question.title %>
  </p>

  <p>
    <%= question.body %>
  </p>

  <p>
    <h2>Answers</h2>
      <% question.answers.map do |answer| %>
        <p>
          <strong>Answered by:</strong>
          <%= answer.author %>
        </p>

        <p>
          <%= answer.body %>
        </p>
          <% answer.corrects.map do |correct| %>
            <% if correct.moderate == true %>
              <p>
                <strong>Corrected by:</strong>
                <%= correct.author %>
              </p>

              <p>
                <%= correct.body %>
              </p>
            <% end %>

              <% if current_user.name == answer.author and correct.moderate == false %>
                <p>
                  <strong>Corrected by:</strong>
                  <%= correct.author %>
                </p>

                <p>
                  <%= correct.body %>
                </p>

                <%= button_to "Submit", { :controller => "corrects", :action => "moderate", :id => correct.id} %>
              <% end %>
          <% end %>

            <%= link_to('Correct', new_question_answer_correct_path(question, answer))  %>
      <% end %>
    <%= link_to('Answer', new_question_answer_path(question)) %>
  </p>

  <hr/>
<% end %>

app/views/questions/new.html.erb
<%= form_for :question, url: {action: "create"} do |f| %>
    <% if @question && @question.errors.any? %>
      <p>
        <ul>
          <% @question.errors.full_messages.each do |msg|%>
            <li><%= msg %> </li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_area :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>
<% end %>